In [1]:
import numpy as np

# resize()

In [3]:
a=np.array([[1,2,3],
           [4,5,6]])

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a_resize=np.resize(a,(3,3))

In [10]:
a_resize

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [11]:
a_resized=np.resize(a,(3,2))

In [12]:
a_resized

array([[1, 2],
       [3, 4],
       [5, 6]])